name: cvpr
channels:
  - defaults
  - conda-forge
  - pytorch
channel_alias: https://mirrors.aliyun.com/anaconda/
show_channel_urls: true

dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip
  - pip:
      - opencv-python
      - tqdm
      - tensorboard
